server {
    server_name lif3line.me www.lif3line.me 146.190.240.66;

    root /var/www/lif3line.me/current;
    index index.html;

    location /assets/ {
        try_files $uri =404;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/lif3line.me/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/lif3line.me/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.lif3line.me) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = lif3line.me) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;
    server_name lif3line.me www.lif3line.me 146.190.240.66;
    return 404; # managed by Certbot
}
