server {
    listen 80;
    listen [::]:80;
    server_name lif3line.me www.lif3line.me 146.190.240.66;

    root /var/www/lif3line.me/current;
    index index.html;

    location /assets/ {
        try_files $uri =404;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
